### ISSUE TITLE
ソフトウェア類にCCライセンスの適用は非推奨とされていますが大丈夫でしょうか？

### ISSUE THREAD

**Issue by Guest126** [Assault-Lily/Lemonade#311]
ライセンスの変更に関するお知らせ #303 で予告の通り、Lemonadeは本日よりMITライセンスからCC BY-NC-SA 4.0ライセンスに移行されました。しかしながら、ソフトウェアの類にCCライセンスを適用することをCreative Commonsは推奨していません。

> #### ソフトウェアにクリエイティブ・コモンズ・ライセンスを適用することはできますか？

> 私たちはソフトウェアにクリエイティブ・コモンズ・ライセンスを適用することをお勧めしません。代わりに、既に利用可能な非常に優れたソフトウェア・ライセンスの一つを利用することを強くお勧めします。私たちは、Free Software Foundationによってフリーとされたライセンスや、Open Source Initiativeによってオープンソースとされたライセンスを検討することをお勧めします。

> ソフトウェア固有のライセンスとは異なり、CCライセンスには、ソフトウェアの自由な再利用と改変可能性を保証するためにしばしば重要となる、ソースコードの配布に関する特定の条項が含まれていません。また、多くのソフトウェアライセンスは特許権も扱っており、これはソフトウェアにとっては重要ですが、他の著作物には適用されない場合があります。さらに、私たちのライセンスは現在、主要なソフトウェアライセンスと互換性がないため、CCライセンスの作品を他のフリーソフトウェアと統合することは困難でしょう。既存のソフトウェアライセンスは、特にソフトウェアで使用するために設計されており、クリエイティブ・コモンズ・ライセンスと同様の権利群を提供しています。

―― [Frequently Asked Questions - Creative Commons](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software)よりDeepL翻訳（[クリエイティブ・コモンズ・ジャパン](https://creativecommons.jp/faq/#a6)による簡易訳もあり）

これらの事情を承知の上でCC BY-NC-SA 4.0を選択されたのであれば構いませんが、もしご存じでなければ再考の余地があるように思われます。

[宮野さんのツイート](https://twitter.com/miyacorata/status/1550869405873356800)によると、

> ライセンスについてですが、CC BY-NC-SAに切り替えたのはMITライセンスのままでは私や公式ではない第三者がLemonadeを商用利用する可能性を排除できなかったための苦渋の決断です。

とのことですが、LuciaDBと違ってLemonadeのソースコードの大半はAZONE INTERNATIONAL・acusの知財とは無関係なロジックであり、第三者に商用利用されて困る部分は『ラスバレ』を模したサイトデザインくらいしか思い当たらず、本当にCC BY-NC-SA 4.0とする必要があったのかという疑問があります。

**Comment by miyacorata** [comment]
ご指摘の通り、CCライセンスは一般にソフトウェアに適用するライセンスとしては推奨されていないものです。
正直私個人としてもPHPで書かれたロジック部分にCCを適用するのには違和感がありましたが、それでもCC BY-NC-SAを選択したのは前述の通り商用利用される可能性を可能な限り排除するという一点につきます。これは原作側との協議の上での選択であり、ご理解賜りたく存じます。

これは個人としての考えですが、ソフトウェアとしてのLemonadeはLuciaDBのデータそのものとは完全に分離されており、CCとは異なるライセンスを選択することも理論上可能であると考えます。LuciaDBは現在 CC BY-NC-SA 4.0 で提供されており、SPARQLでエンドポイントを叩くときにCCライセンスへの遵守が求められます。それが遵守される限りはLemonadeは異なるOSSライセンスを選択することが可能であり、LuciaDBのライセンスが守られることを大前提とできればMPL等のライセンスを適用することもできたかと思います。

追加で申し上げますと、[CCライセンスは一度つけたものは取り消しができません](https://creativecommons.jp/faq/#b16)。つまり、このライセンスに変わった時点でCCライセンス以外への変更は今後行われることはなく、リポジトリの非公開化もしくは削除というアクション以外でソースコードの提供方法が変わることはありません。

**Comment by Guest126** [comment]
確かに一度CCライセンスをつけたバージョンは取り消しできませんが、まださほど変更は積み上がっていませんので、MITライセンスの最終バージョンからForkするか、主要貢献者の了解の下（つまり宮野さんの一存）でCC BY-NC-SA 4.0とMITのデュアルライセンスにするといったことは可能であると思われます。

もっとも原作側との協議の上ということであればこれ以上とやかく言う必要はないと思いますのでclose方向で。
