### ISSUE TITLE
LuciaDB更新情報欄に不要なリンクが生成されている

### ISSUE THREAD

**Issue by ulong32** [Assault-Lily/Lemonade#389]
![IMG_0646](https://user-images.githubusercontent.com/64057266/234821453-71180975-270f-4d5f-8dde-fa4fc30064e9.jpeg)

上記画像のように、本来不要な箇所にLへのリンクが生成されてしまっています。

**Comment by fvh-P** [comment]
認識してますー
直せなくね……？？？ってなって困り果ててます😭

**Comment by ulong32** [comment]
少し考えてみたのですけど、
- LuciaDBのコミット名規約を作る（Lについてのコミットなら、何かしらのIdentifierをつけるなど）
- あきらめてLについてのリンク生成は除外する

おそらくすでに考えているとは思いますし、どれもあまりスマートな解決方法ではないですが...

**Comment by miyacorata** [comment]
個人的な見解ですが、"L"の一文字というのが厄介すぎるのでリンク生成から除外しても致し方ないかなと思うところはあります。本当はしたくないのですが...

Lemonadeの都合でLuciaDBのコミット名等に制約を設けるのは良くないと思いますので、それは避けたいですね。

**Comment by ulong32** [comment]
正直なところ、Lは故人ですし、新情報もあまりなさそうですので、リンク生成を除外してもあまり影響はない気がします。
今回のバグが顕在化したLily Projectもこれからなので、除外したほうが良いのかな？とは思います。

**Comment by ulong32** [comment]
#413 にて解決しましたのでクローズします。
